//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6413
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualPhaseCalculation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualPhaseCalculation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;systems&gt;
        ///	&lt;system&gt;
        ///		&lt;leftElement id=&quot;Pu&quot;/&gt;
        ///		&lt;rightElement id=&quot;U&quot;/&gt;
        ///		&lt;azeotrope&gt;
        ///			&lt;temperature&gt;900&lt;/temperature&gt;
        ///			&lt;coordinate&gt;0.0978&lt;/coordinate&gt;
        ///		&lt;/azeotrope&gt;
        ///		&lt;experimental&gt;
        ///			&lt;temperature&gt;1173&lt;/temperature&gt;
        ///			&lt;liquidusCoordinate&gt;0.596&lt;/liquidusCoordinate&gt;
        ///			&lt;solidusCoordinate&gt;0.682&lt;/solidusCoordinate&gt;
        ///		&lt;/experimental&gt;
        ///	&lt;/system&gt;
        ///	
        ///	&lt;system&gt;
        ///		&lt;leftElement id=&quot;Fe&quot;/&gt;
        ///		&lt;rightElement id=&quot;Cr&quot;/&gt;
        ///		&lt;azeotrope&gt;
        ///			&lt;temperature&gt;1786&lt;/temper [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BinarySystemsData {
            get {
                return ResourceManager.GetString("BinarySystemsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt; 
        ///&lt;elements&gt;
        ///	&lt;element&gt;
        ///		&lt;name&gt;Fe&lt;/name&gt;
        ///		&lt;phaseChange&gt;
        ///			&lt;temperature&gt;1811&lt;/temperature&gt;
        ///			&lt;enthalpy&gt;13806&lt;/enthalpy&gt;
        ///			&lt;entropy&gt;7.6241&lt;/entropy&gt;
        ///			&lt;heatCapacityChange&gt;4.6537&lt;/heatCapacityChange&gt;
        ///		&lt;/phaseChange&gt;
        ///	&lt;/element&gt;
        ///	&lt;element&gt;
        ///		&lt;name&gt;Cr&lt;/name&gt;
        ///		&lt;phaseChange&gt;
        ///			&lt;temperature&gt;2180&lt;/temperature&gt;
        ///			&lt;enthalpy&gt;21004&lt;/enthalpy&gt;
        ///			&lt;entropy&gt;9.6349&lt;/entropy&gt;
        ///			&lt;heatCapacityChange&gt;-10.7118&lt;/heatCapacityChange&gt;
        ///		&lt;/phaseChange&gt;
        ///	&lt;/element&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ElementsData {
            get {
                return ResourceManager.GetString("ElementsData", resourceCulture);
            }
        }
    }
}
